# Generated by Django 4.2.5 on 2023-09-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='path',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
