# Generated by Django 4.2.5 on 2023-09-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_media_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='path',
            field=models.ImageField(upload_to=''),
        ),
    ]
