# Generated by Django 4.2.5 on 2023-09-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_alter_media_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='duration',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='offer',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='offer',
            name='start_date',
            field=models.DateField(default=None),
        ),
    ]
